### ISSUE TITLE
description.title in config file is not accepted as schema validation error

### ISSUE THREAD

**Issue by DavidBiesack** [robertmassaioli/openapi-merge#46]
Using:

```bash
$ openapi-merge-cli --version
1.3.1
```

Given this config file `openapi-merge.yaml` :

```yaml
inputs:
  - inputFile: a.yaml
    description:
      append: true
      title: Customer Accounts
  - inputFile: bi.yaml
    description:
      append: false
output: ../gen/openapi.yaml
```

when running 

```bash
openapi-merge-cli --config openapi-merge.yaml
```

I get an error

```
data.inputs[0].description.title should be object, data.inputs[0] should NOT have additional properties, data.inputs[0].description.title should be object, data.inputs[0] should NOT have additional properties, data.inputs[0] should match some schema in anyOf
```

If I remove the `title:` line, there is no error

In the distribution, the `configuration.schema.json` has a `DescriptionTitle` schema with

```
            "title": "DescriptionTitle",
            "type": "object"
```

which I think should be `"type": "string"`

The documentation says:

```
description.title: An optional field, that lets you spefify a custom heading for this inputs description when it is merged together in the output OpenAPI file.
```

but does not describe this as an object.

After looking at the code I was able to get this to work by using `description.title.value`

```yaml
inputs:
  - inputFile: a.yaml
    description:
      append: true
      title:
        value: Customer Accounts
  - inputFile: bi.yaml
    description:
      append: false
output: ../gen/openapi.yaml
```

See `src/examples-for-schema.ts` which has examples showing a title.headingLevel is also supported; `headingLevel: 6`

So it looks like the doc is incorrect. I can file a PR.
